<?php
/**
 * OrganizationSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrganizationSettings Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationSettings implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrganizationSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'default_dst_expire_days' => 'int',
        'default_language' => 'string',
        'alfresco_properties' => '\OpenAPI\Client\Model\OrganizationSettingsAlfrescoProperties'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'default_dst_expire_days' => 'int32',
        'default_language' => null,
        'alfresco_properties' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default_dst_expire_days' => 'defaultDSTExpire_days',
        'default_language' => 'defaultLanguage',
        'alfresco_properties' => 'alfrescoProperties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default_dst_expire_days' => 'setDefaultDstExpireDays',
        'default_language' => 'setDefaultLanguage',
        'alfresco_properties' => 'setAlfrescoProperties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default_dst_expire_days' => 'getDefaultDstExpireDays',
        'default_language' => 'getDefaultLanguage',
        'alfresco_properties' => 'getAlfrescoProperties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const DEFAULT_LANGUAGE_IT = 'it';
    const DEFAULT_LANGUAGE_EN = 'en';
    const DEFAULT_LANGUAGE_ES = 'es';
    const DEFAULT_LANGUAGE_FR = 'fr';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDefaultLanguageAllowableValues()
    {
        return [
            self::DEFAULT_LANGUAGE_IT,
            self::DEFAULT_LANGUAGE_EN,
            self::DEFAULT_LANGUAGE_ES,
            self::DEFAULT_LANGUAGE_FR,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['default_dst_expire_days'] = isset($data['default_dst_expire_days']) ? $data['default_dst_expire_days'] : 30;
        $this->container['default_language'] = isset($data['default_language']) ? $data['default_language'] : null;
        $this->container['alfresco_properties'] = isset($data['alfresco_properties']) ? $data['alfresco_properties'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDefaultLanguageAllowableValues();
        if (!is_null($this->container['default_language']) && !in_array($this->container['default_language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'default_language', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets default_dst_expire_days
     *
     * @return int|null
     */
    public function getDefaultDstExpireDays()
    {
        return $this->container['default_dst_expire_days'];
    }

    /**
     * Sets default_dst_expire_days
     *
     * @param int|null $default_dst_expire_days default_dst_expire_days
     *
     * @return $this
     */
    public function setDefaultDstExpireDays($default_dst_expire_days)
    {
        $this->container['default_dst_expire_days'] = $default_dst_expire_days;

        return $this;
    }

    /**
     * Gets default_language
     *
     * @return string|null
     */
    public function getDefaultLanguage()
    {
        return $this->container['default_language'];
    }

    /**
     * Sets default_language
     *
     * @param string|null $default_language default_language
     *
     * @return $this
     */
    public function setDefaultLanguage($default_language)
    {
        $allowedValues = $this->getDefaultLanguageAllowableValues();
        if (!is_null($default_language) && !in_array($default_language, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'default_language', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['default_language'] = $default_language;

        return $this;
    }

    /**
     * Gets alfresco_properties
     *
     * @return \OpenAPI\Client\Model\OrganizationSettingsAlfrescoProperties|null
     */
    public function getAlfrescoProperties()
    {
        return $this->container['alfresco_properties'];
    }

    /**
     * Sets alfresco_properties
     *
     * @param \OpenAPI\Client\Model\OrganizationSettingsAlfrescoProperties|null $alfresco_properties alfresco_properties
     *
     * @return $this
     */
    public function setAlfrescoProperties($alfresco_properties)
    {
        $this->container['alfresco_properties'] = $alfresco_properties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


