<?php
/**
 * IdentityProviderDataTokenInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Signing Today Web
 *
 * *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * IdentityProviderDataTokenInfoTest Class Doc Comment
 *
 * @category    Class
 * @description IdentityProviderDataTokenInfo
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IdentityProviderDataTokenInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IdentityProviderDataTokenInfo"
     */
    public function testIdentityProviderDataTokenInfo()
    {
    }

    /**
     * Test attribute "ul_min_pin_len"
     */
    public function testPropertyUlMinPinLen()
    {
    }

    /**
     * Test attribute "manufacturer_id"
     */
    public function testPropertyManufacturerId()
    {
    }

    /**
     * Test attribute "ul_free_public_memory"
     */
    public function testPropertyUlFreePublicMemory()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "ul_total_public_memory"
     */
    public function testPropertyUlTotalPublicMemory()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "flags"
     */
    public function testPropertyFlags()
    {
    }

    /**
     * Test attribute "ul_total_private_memory"
     */
    public function testPropertyUlTotalPrivateMemory()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "ul_free_private_memory"
     */
    public function testPropertyUlFreePrivateMemory()
    {
    }

    /**
     * Test attribute "ul_max_pin_len"
     */
    public function testPropertyUlMaxPinLen()
    {
    }
}
